export interface InvoiceData {
  id?: string;
  " AvidPay Check #": string;
  " Cash Account": string;
  " Cleared Date": string;
  " Delivery Method": string;
  " Delivery Status": string;
  " G/L Amount": string;
  " Invoice Count": string;
  " Last Update Date": string;
  " Pay TransactionId": string;
  " Payment Amount": string;
  "Bank Account": string;
  "Check": string;
  "Code": string;
  "Company": string;
  "Date Paid": string;
  "G/L Account": string;
  "Invoice Amount": string;
  "Invoice Id": string;
  "Invoice Num": string;
  "Vendor": string;
  "checkStubNote": string;
  "dueDate": string;
  "internalNote": string;
  "invoiceDate": string;
  "pdfId": string;
  "topsRef": string;
  "trxnDate": string;
}